label ruby_jacuzzisex_scene:
    play music MUSIC_SEXY_THEME
    scene rubyjacuzzisex01 with fade
    Jimmy "Wow, this is really nice."
    Ruby "Yes! It's so good to have a jacuzzi. I feel like everyone should have one in their house."
    Jimmy "You know what's even better?"
    Ruby "What?"
    Jimmy "Sharing it with a pretty girl."
    Ruby "..."
    Ruby "Oh... my... god. THAT WAS SO CUTE!"
    Ruby "I... I'm not used to hanging out with people like you."
    Ruby "I'm kind of curious about something..."
    Jimmy "About what?"
    Ruby "It is said that poor people are more fertile and, particularly men, have more... Manhood in them."
    "WTF?"
    Jimmy "Well, um. I'm not sure about that."
    Ruby "Can I see your penis?"
    Jimmy "Wow! That was quick."
    Ruby "I'm just curious, don't blame me."
    Ruby "Listen, let's make deal. I get naked and you get naked too and we can drink some champagne and see what happens."
    Jimmy "Well, that's not a bad idea."
    scene rubyjacuzzisex02 with dissolve
    Ruby "Have you ever tried Chardonnay?"
    Jimmy "Chardo-what? That sounds like a Pokémon."
    Ruby "Ha, ha! That's so funny. What's a Pokémon?"
    "This girl is denser than a bucket of bricks."
    Jimmy "Nevermind, don't worry about it."
    Jimmy "Your boobs are beautiful, my lady."
    Ruby "Thank you, my lord."
    Ruby "Now I know guys like you actually have really big penises."
    Jimmy "Well, not everyone, really."
    Ruby "How does it feel to have sex with such a huge thing?"
    Jimmy "I think it's more about the way you move your hips and the positions used."
    Jimmy "If you don't know how to please a girl, having a big penis doesn't make a difference."
    Ruby "Are you an expert in sex?"
    Jimmy "Not sure, but I do know how to please a girl."
    Ruby "I'm getting a bit tipsy with this wine."
    Ruby "Do you like the jacuzzi so far?"
    Jimmy "I like YOU so far."
    Ruby "Mmm, good answer."
    Ruby "I feel like I want to try something."
    Jimmy "What is it?"
    scene rubyjacuzzisex03 with vpunch
    "Ruby got up and jumped on [player_name] like a wild animal trying to eat its prey."
    "They kissed with such passion thanks to the warmness of the water and the mix of alcohol and dirty thoughts."
    Ruby "I want to sit on your penis, under one condition."
    Ruby "You won't say a word about this to anyone."
    Ruby "My reputation is at stake here, so can you promise?"
    Jimmy "You have my word, my lady."
    Ruby "That's enough for me. I'm just too horny."
    scene rubyjacuzzisex04 with fade
    Ruby "Alright, please be careful and put it inside me slowly."
    Ruby "Then, I'll just sit on it."
    Jimmy "Alright, here we go."
    Ruby "OOOOhhh my god."
    Ruby "My pussy is burning."
    Jimmy "Oh, yeah. I can tell. It barely fits."
    Ruby "Uff, just like that, leave it right there."
    Ruby "Here we go... One... Two..."
    scene rubyjacuzzisex05 with vpunch
    Ruby "OOHHH MY LOOORD!!"
    Ruby "Bloody hell!! I can feel it right up in my belly."
    Ruby "Fuck, it feels so good."
    Ruby "Stay right there. I'm just gonna fuck this cock 'til I cum."
    Jimmy "Be my guest."
    scene rubyjacuzzisex06 with dissolve
    Ruby "YES! YESSS! It's so good."
    Ruby "I never thought fucking a peasant would be this great!"
    "What a fucking bitch, but her pussy is so fucking hot. I don't mind, baby, ride me!"
    Ruby "Fuck, I'm gonna CUM!"
    scene rubyjacuzzisexcum with vpunch
    Ruby "[player_name], that was wonderful!"
    Ruby "I think I'm gonna try to hang out with the common people a bit more."
    Ruby "Remember, not a word about this and maybe we'll see each other again."
    if rubygallery == True:
        call screen rubygallery
    return
