label queenletticiarescueintro:
    hide screen freeroamhud
    play music "audio/music/investigationfunny.ogg"
    scene auditoriumhallfallevening with fade
    show miku servant sad with moveinright
    "{i}When entering the Auditorium, [player_name] saw Miku in a corner wearing an old dress and doing exaggerated gestures to herself."
    play sound "audio/sfx/frustratedhum.ogg"
    Miku "Oh, woe is me! The Queen languishes! Her royal spirit, once a lion's roar, now but a gentle sigh!"
    Jimmy "..."
    play sound "audio/sfx/gasp01.ogg"
    Miku "Hark! A uniform! A shield of valor! My liege, you have arrived at the hour of our greatest need!"
    Miku "Blessed be the heavens, for they have sent a Royal Guard in our darkest hour!"
    Jimmy "Uhhh... What are you...?"
    Miku "Good sir, you are the embodiment of Queen Letticia's last hope! The bastion against the usurper's tyranny!"
    Jimmy "Oh, Eunice's play, right?"
    play sound "audio/sfx/girlsigh01.ogg"
    Miku "Our beloved Queen, imprisoned by that villainous Count, grows weaker by the hour! Her royal constitution, once robust as an oak, now wilts like a forgotten lettuce leaf!"
    Jimmy "Wow, you're really into character."
    play sound "audio/sfx/whisperfemale.ogg"
    Miku "{i}*whispering* Come on, just follow my lead.{/i}"
    Miku "Only one elixir can restore her strength, can rekindle the fire in her royal gaze! A draught of pure, creamy... milk!"
    Miku "But alas! Our Queen, adheres to the sacred vows of the herbivore! She refuses all that flows from creature!"
    Jimmy "She's... vegan?"
    Miku "Precisely! A virtue in times of peace!"
    play sound "audio/sfx/hmm01.ogg"
    Miku "I have tried, good Guard! I have pleaded! I have even disguised the milk as 'cloud nectar'! But her resolve is unyielding!"
    Miku "And without her full strength, how can she save Sir Laughsalot from the clutches of the usurper?"
    play sound "audio/sfx/clearthroat01.ogg"
    Jimmy "Sir Laughsalot? Oh, no! I love that chicken."
    Miku "Me too! You must help us! You, with your honest face and your aura of unwavering loyalty! You must convince the Queen to drink the milk!"
    Miku "Then, with her strength returned, we shall break her from her prison, defeat the usurper, and rescue our squawking, sacred champion!"
    Miku "Will you aid your Queen, Sir Knight? Will you answer the call of duty?"
    Jimmy "This is... a lot. But, yeah, sure. I can help."
    Miku "At once! Come with me, I know a secret way into the dungeon."
    play sound "audio/sfx/run01.ogg"
    scene auditoriumbackstage01 with fade
    "{i}Miku pushes aside a heavy velvet curtain, revealing the familiar backstage area. In the dim, dusty light, it looks less like a workshop and more like a grim, forgotten catacomb.{/i}"
    Miku "{i}*whispering* Tread carefully, good Guard. The usurper's spies are everywhere.{/i}"
    play sound "audio/sfx/hmm02.ogg"
    Miku "The Queen is being held in the deepest cell... Umm, 'Prop Storage Closet B'."
    "{i}She leads you to a dark corner, partially blocked by a large, painted flat of a spooky-looking tree. From behind it, you hear a faint, sorrowful sigh.{/i}"
    scene queenletticiaprisoner with fade
    play music "audio/music/classicmusic01.ogg"
    Eunice "Is that you, Matilda? Have you come to watch the last flicker of my royal light extinguish?"
    Miku "My Queen! I have brought help! A member of your Royal Guard, still loyal to the true crown!"
    play sound "audio/sfx/surprisedhum.ogg"
    Eunice "Oh, Sir... you came. To see me one last time before my tragic end. Your loyalty... it warms the cold stone of this wretched prison."
    Jimmy "Uh, yeah. End? You're not... actually dying, are you?"
    play sound "audio/sfx/girlsigh01.ogg"
    Miku "She will be if she does not regain her strength! My Queen, I beg of you!"
    Miku "Please, you must drink it! For your kingdom! For Sir Laughsalot!"
    play sound "audio/sfx/frustratedhum.ogg"
    Eunice "Matilda, you know my vow. I cannot. My principles are all I have left."
    Jimmy "Look, Eunice—I mean, Your Majesty. Miku's right. You gotta drink the milk."
    Jimmy "You'll feel better, and then we can figure out how to get you out of here and save the... chicken."
    Eunice "Your words are... strangely blunt, Sir [player_name]. Yet, perhaps with your help there is some hope."
    Eunice "Very well. For the kingdom. I will... I will do it. Bring me the chalice."
    Miku "Yes! At last! Your strength will be renewed, my Queen!"
    play sound "audio/sfx/stopmusiceffect.ogg"
    stop music
    "{i}Miku's anxiously pulls out the glass of milk, but immediately drops it and it turns into a white pool of broken glass on the ground.{/i}"
    play sound "audio/sfx/glassbrake.ogg"
    scene queenletticiaprisonermilk with vpunch
    Miku "No! Catastrophe! The chalice!"
    play sound "audio/sfx/crowdshock01.ogg"
    Miku "Oh, cruel fate! The Queen's only hope, shattered into a thousand milky shards!"
    Eunice "It seems the heavens have made their decision. My reign is truly over."
    play sound "audio/sfx/clearthroat01.ogg"
    Jimmy "Well, I guess we tried."
    Miku "No! We just need to find another kind. Maybe we can get milk from someone else?"
    Jimmy "Uhh..."
    play sound "audio/sfx/girlsigh01.ogg"
    Miku "Yes, you are a strong virile man. You can give us the milk we need!"
    Jimmy "Me? What milk can I... Oh..."
    play sound "audio/sfx/hmm03.ogg"
    Eunice "That's a great idea, Matilda. His milk can be even more useful than regular cow milk."
    Eunice "Please, my lord. Can you give us your milk?"
    Jimmy "Umm, okay, sure."
    Eunice "Quickly, Matilda. We need to arouse this man, in order to harden the source of his milk."
    Eunice "We need to extract the elixir ourselves."
    Miku "Of course, my queen. Anything for you."
    play sound "audio/sfx/sexyintro.ogg"
    call miku_queenrescue3some_scene from _call_miku_queenrescue3some_scene
    play music MUSIC_MIKUS_THEME
    scene auditoriumbackstage01 with fade
    show miku servant happy with dissolve
    play sound "audio/sfx/giggle01.ogg"
    Miku "Thank you so much, [player_name]."
    Jimmy "You too are going to get me in trouble on of this days."
    play sound "audio/sfx/laugh01.ogg"
    Miku "Ha, ha, ha, you're right. We need to be careful."
    Miku "I'm just trying, you know, to help my best friend be more confident with herself."
    Jimmy "I get it. I'm glad I helped."
    Miku "For now she needs to focus on her play, so no more crazy stuff in a while."
    Miku "By the way, now that you are getting to know the guys."
    Miku "I hope you join us at the library for the ending of the Grottos and Gremlins campaign."
    play sound "audio/sfx/laugh02.ogg"
    Jimmy "Oh, yeah. I'm eager to join the order of Felattion, ha, ha, ha."
    Miku "Ha, ha, ha, come on. It's not that bad. It will be fun, I promise."
    Jimmy "Alright, I'll think about it."
    Miku "Great, see you later. I'm gonna help Eunice clean the mess."
    $ quests.euniceTheaterpractice = COMPLETE
    call nexttime from _call_nexttime_51
    $ gotoscene('mainbuildingrighthallway', transition=fade)
